# Generated by Django 4.2.2 on 2023-07-25 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ürün İsmi')),
                ('content', models.TextField(verbose_name='Ürün Açıklaması')),
                ('price', models.IntegerField(verbose_name='Ürün Fiyatı')),
                ('image', models.ImageField(upload_to='product/', verbose_name='Ürün Resmi')),
                ('slug', models.SlugField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Satıcı')),
            ],
        ),
    ]
