# Generated by Django 4.2.2 on 2023-07-25 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('urunler', '0002_alter_product_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Adet')),
                ('totalPrice', models.IntegerField(verbose_name='Toplam Fiyat')),
                ('isPayment', models.BooleanField(default=False, verbose_name='Ödendi mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ekleyen')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urunler.product', verbose_name='Eklenen Ürün')),
            ],
            options={
                'verbose_name': 'Sepet',
                'verbose_name_plural': 'Sepetteki Ürünler',
            },
        ),
    ]
